server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      default-filters: # default-filters下的过滤器可以作用于所有路由
        - JwtToken
      routes:
        - id: admin # 路由规则id，自定义，唯一
          uri: lb://gas-admin # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/admin/** # 这里是以请求路径作为判断规则
        - id: user
          uri: lb://gas-user
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/user/** # 这里是以请求路径作为判断规则
        - id: pipelines
          uri: lb://gas-pipelines
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/pipelines/** # 这里是以请求路径作为判断规则
        - id: report
          uri: lb://gas-report
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/report/** # 这里是以请求路径作为判断规则


